/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espoch.sistemaacademicopao2.vistas;

import ec.edu.espoch.sistemaacademicopao2.controlador.ControladorDecano;
import ec.edu.espoch.sistemaacademicopao2.decanos.Decano;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionListener;

public class VDecanos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VDecanos.class.getName());

    private ControladorDecano controladorDecano;
    private DefaultTableModel modeloTabla;
    


    public VDecanos() {
        initComponents();
        this.controladorDecano = new ControladorDecano();
        modeloTabla = new DefaultTableModel(new String[]{
            "ID", "Nombre", "Cédula", "Correo Inst.", "Correo Pers.","Nivel", "Sueldo"
        }, 0);

        jTableDecano.setModel(modeloTabla);
        jTableDecano.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) { 
                if (!e.getValueIsAdjusting()) {
                    cargarDecanoSeleccionado();
                }
            }

            private void cargarDecanoSeleccionado() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblV_Decanos = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jBtnV_Agregar = new javax.swing.JButton();
        jBtnV_Actaulizar = new javax.swing.JButton();
        jBtnV_Eliminar = new javax.swing.JButton();
        jBtnV_Cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDecano = new javax.swing.JTable();
        jBtnV_Guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblV_Decanos.setText("DECANOS");

        jLabel2.setText("ID:");

        jLabel3.setText("Nivel:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Cedula:");

        jLabel6.setText("CorreoPersonal:");

        jLabel7.setText("CorreoInstitucional:");

        jLabel8.setText("Sueldo:");

        jBtnV_Agregar.setText("AGREGAR");

        jBtnV_Actaulizar.setText("ACTUALIZAR");
        jBtnV_Actaulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV_ActaulizarActionPerformed(evt);
            }
        });

        jBtnV_Eliminar.setText("ELIMINAR");
        jBtnV_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV_EliminarActionPerformed(evt);
            }
        });

        jBtnV_Cerrar.setText("CERRAR");

        jTableDecano.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NIVEL", "NOMBRE", "CEDULO", "CORREOP", "CORREOINS", "SUELDO"
            }
        ));
        jScrollPane1.setViewportView(jTableDecano);

        jBtnV_Guardar.setText("GUARDAR");
        jBtnV_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV_GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6)
                            .addComponent(jTextField7))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnV_Agregar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnV_Actaulizar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnV_Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnV_Guardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnV_Cerrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLblV_Decanos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLblV_Decanos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnV_Agregar)
                            .addComponent(jBtnV_Actaulizar)
                            .addComponent(jBtnV_Eliminar)
                            .addComponent(jBtnV_Cerrar)
                            .addComponent(jBtnV_Guardar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnV_ActaulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV_ActaulizarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBtnV_ActaulizarActionPerformed

    private void jBtnV_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnV_GuardarActionPerformed

    private void jBtnV_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV_EliminarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBtnV_EliminarActionPerformed

    public String getId(){
        return jTextField1.getText();
    }
    public String getNivel() {
        return jTextField2.getText();
    }
    public String getNombre() {
        return jTextField3.getText();
    }
    public String getCedula() {
        return jTextField4.getText();
    }
    public String getCorreoPersonal() {
        return jTextField5.getText();
    }
    public String getCorreoInstitucional() {
        return jTextField6.getText();
    }
    public String getSueldo(){
        return jTextField7.getText();
    }
    public JTable getTabla() {
        return jTableDecano;
    }
    
    //setter
    
    public void setNivel(String nivel){
        jTextField2.setText(nivel);
    }
    public void setNombre(String nombre){
        jTextField3.setText(nombre);
    }
    public void setCedula(String Cedula){
        jTextField4.setText(Cedula);
    }
    public void setCorreoPersonal(String CorreoPersonal){
        jTextField5.setText(CorreoPersonal);
    }
    public void setCorreoInstitucional(String CorreoInstitucional){
          jTextField6.setText(CorreoInstitucional);
    }
    public void setSueldo(String Sueldo){
          jTextField7.setText(Sueldo);
    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnV_Actaulizar;
    private javax.swing.JButton jBtnV_Agregar;
    private javax.swing.JButton jBtnV_Cerrar;
    private javax.swing.JButton jBtnV_Eliminar;
    private javax.swing.JButton jBtnV_Guardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblV_Decanos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDecano;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
